export const FETCH_TRADES_REQUEST = "FETCH_TRADesS_REQUEST";
export const FETCH_TRADES_SUCCESS = "FETCH_TRADES_SUCCESS";
export const FETCH_TRADES_FAIL = "FETCH_TRADES_FAIL";

export const TRADE_DETAILS_REQUEST = "ROOM_DETAILS_REQUEST";
export const TRADE_DETAILS_SUCCESS = "ROOM_DETAILS_SUCCESS";
export const TRADE_DETAILS_FAIL = "ROOM_DETAILS_FAIL";

export const TRADE_CREATE_REVIEW_REQUEST = "ROOM_CREATE_REVIEW_REQUEST";
export const TRADE_CREATE_REVIEW_SUCCESS = "ROOM_CREATE_REVIEW_SUCCESS";
export const ROOM_CREATE_REVIEW_FAIL = "ROOM_CREATE_REVIEW_FAIL";

export const CREATE_TRADE_REQUEST = "CREATE_TRADE_REQUEST";
export const CREATE_TRADE_SUCCESS = "CREATE_TRADE_SUCCESS";
export const CREATE_TRADE_FAIL = "CREATE_TRADE_FAIL";
export const CREATE_TRADE_RESET = "CREATE_TRADE_RESET";

export const UPDATE_TRADE_REQUEST = "UPDATE_ROOM_REQUEST";
export const UPDATE_TRADE_SUCCESS = "UPDATE_ROOM_SUCCESS";
export const UPDATE_TRADE_FAIL = "UPDATE_ROOM_FAIL";
export const UPDATE_TRADE_RESET = "UPDATE_ROOM_RESET";

export const DELETE_TRADE_REQUEST = "DELETE_ROOM_REQUEST";
export const DELETE_TRADE_SUCCESS = "DELETE_ROOM_SUCCESS";
export const DELETE_TRADE_FAIL = "DELETE_ROOM_FAIL";
export const DELETE_TRADE_RESET = "DELETE_ROOM_RESET";


